In [1]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [2]:
iris = load_iris()
X = iris.data
y = iris.target

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [6]:
std_enc=StandardScaler()
X_train = std_enc.fit_transform(X_train)
X_test = std_enc.transform(X_test)

In [8]:
X_train

array([[ 0.56195149,  0.55613693,  0.51790028,  0.51008192],
       [ 0.80278784, -0.13265651,  1.14418849,  1.30158834],
       [-0.28097574, -1.28064558,  0.06241795, -0.14950677],
       [-0.16055757, -0.59185214,  0.4040297 ,  0.11432871],
       [ 0.68236966, -0.59185214,  1.03031791,  1.30158834],
       [-1.36473933,  0.32653911, -1.24709376, -1.3367664 ],
       [ 0.32111514, -0.13265651,  0.63177087,  0.77391739],
       [-1.0034848 ,  0.78573474, -1.24709376, -1.07293093],
       [ 0.68236966, -0.59185214,  1.03031791,  1.1696706 ],
       [ 2.4886423 ,  1.70412599,  1.48580024,  1.03775287],
       [ 1.04362419, -0.13265651,  0.80257674,  1.43350608],
       [ 1.04362419, -1.28064558,  1.14418849,  0.77391739],
       [ 1.16404237,  0.32653911,  1.20112378,  1.43350608],
       [-1.24432115, -0.13265651, -1.36096434, -1.20484867],
       [-1.24432115,  0.0969413 , -1.24709376, -1.3367664 ],
       [-1.4851575 ,  1.24493037, -1.58870551, -1.3367664 ],
       [-0.16055757,  3.

In [9]:
model = SVC()
model.fit(X_train, y_train)

SVC()

In [10]:
y_pred = model.predict(X_train)

In [11]:
y_pred

array([1, 2, 1, 1, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1,
       0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0,
       1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2,
       0, 0, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0,
       2, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0,
       1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2,
       0, 1, 2])

In [12]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train, y_pred)

0.9777777777777777

In [13]:
from sklearn.multiclass import OneVsRestClassifier

ovr_clf = OneVsRestClassifier(SVC(random_state=42))
ovr_clf.fit(X_train, y_train)

OneVsRestClassifier(estimator=SVC(random_state=42))

In [14]:
from sklearn.linear_model import LogisticRegression

log_regv = LogisticRegression()
log_regv.fit(X_train, y_train)

LogisticRegression()

One versus Rest Classification

In [15]:
import numpy as np

In [ ]:
class LogisticRegression:
    """Support both binary and multiclass classification"""
    def __init__(self):
        pass
    def fit(self, lr=0.001, tol = 0.0001, max_iter=1000):
        self.lr=lr
        self.tol=tol
        self.max_iter=max_iter
    def fit(self, X, y):
        n=X_train.shape[0]
        y_pred = np.zeros(n)

    def predict(self, X):
        pass



In [49]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def binary_cross_entropy(y, y_pred):
    m = y.shape[0]
    epsilon = 1e-8 
    return -1/m * np.sum(
        y * np.log(y_pred + epsilon) + (1 - y) * np.log(1 - y_pred + epsilon)
    )

class LogisticRegression:
    def __init__(self, lr=0.001, tol=1e-4, max_iter=1000):
        self.lr = lr
        self.tol = tol
        self.max_iter = max_iter
        self.W = None
        self.b = None
    
    def fit_binary(self, X, y):
        #shape of X: (n,m)
        #n-observations
        #m-features

        #shape of y: n
        #there are 2 distinct classes: 0 and 1
        X = np.array(X)
        y = np.array(y)
        m, n = X.shape  

        w = np.random.randn(n, 1)
        b = 0

        y = y.reshape(m, 1)
        for _ in range(self.max_iter):
            z = X @ w + b
            y_pred = sigmoid(z)
            dw = (1/m) * (X.T @ (y_pred - y))
            db = (1/m) * np.sum(y_pred - y)
            w -= self.lr * dw
            b -= self.lr * db
            if np.linalg.norm(dw) < self.tol and abs(db) < self.tol:
                break
        return w, b
    
    def fit(self, X, y):
        #shape of X: (n,m)
        #n-observations
        #m-features
        X=np.array(X)
        y=np.array(y)

        #shape of y: n
        #there are c distinct classes: 0 and 1

        self.W = []
        self.b=[]

        classes = np.unique(y)
        self.n_classes = len(classes)

        for class_ in classes:
            y_binary = y==class_
            w, b = self.fit_binary(X, y_binary)

            self.W.append(w)
            self.b.append(b)
        
    def predict_binary(self, X, w, b):
        logits = X@w+b
        probs = sigmoid(logits)
        return probs
    
    def predict(self, X):
        n = X.shape[0]
        all_probs=[]
        for w,b in zip(self.W, self.b):
            prob = self.predict_binary(X,w,b)
            all_probs.append(prob)
        return np.stack(all_probs, axis=1).reshape(n, self.n_classes).argmax(axis=1)

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

In [50]:
log_reg.predict(X_train[0:2])

array([2, 2])

In [43]:
all_probs

[array([[0.48558301],
        [0.32273678]]),
 array([[0.11984207],
        [0.09774468]]),
 array([[0.71053905],
        [0.31925081]])]

In [ ]:
n = X_train[0:2].shape[0]
n_classes = 3
np.stack(all_probs, axis=1).reshape(n, n_classes).argmax(axis=1)

array([[0.48558301, 0.11984207, 0.71053905],
       [0.32273678, 0.09774468, 0.31925081]])

In [52]:
logits = np.array([3,4,2])
probs = np.exp(logits)/np.exp(logits).sum()

In [54]:
probs

array([0.24472847, 0.66524096, 0.09003057])

In [53]:
probs.sum()

np.float64(0.9999999999999999)

In [73]:
from sklearn.preprocessing import OneHotEncoder

y_train_one_hot = OneHotEncoder().fit_transform(y_train.reshape(-1,1))

In [74]:
n_features = X_train.shape[1]
n, n_classes = y_train_one_hot.shape
print(f"{n_features=}")
print(f"{n=}")
print(f"{n_classes=}")

n_features=4
n=135
n_classes=3


In [75]:
W = np.random.randn(n_features,n_classes)
W

array([[ 0.27241559, -0.56990564, -0.17318333],
       [ 0.17652085, -0.16714222,  0.50308765],
       [ 0.27946279, -0.08921803, -1.07865833],
       [ 0.48501809, -1.14189403, -0.56677211]])

In [ ]:
def softmax(x):
    return np.exp(logits)/np.exp(logits).sum(axis=1, keepdims=True)

In [87]:
def cross_entropy(probs, y_true):
    n=probs.shape[0]
    return -(np.log(probs)*y_true).sum()/n



In [89]:
np.random.seed(42)
lr=0.001
lossi=[]
b = np.zeros(n_classes)
print(f"{W=}")
print(f"{b=}")

for _ in range(1):
    logits = X_train @ W + b
    probs = softmax(logits)

    #Calculate loss
    loss = cross_entropy(probs, y_train_one_hot)
    lossi.append(loss)

    dW = X_train.T @ (probs - y_train_one_hot)/n
    db= np.sum(probs - y_train_one_hot, axis=0)/n

    W -= lr.dW
    b-= lr.db


W=array([[ 0.27241559, -0.56990564, -0.17318333],
       [ 0.17652085, -0.16714222,  0.50308765],
       [ 0.27946279, -0.08921803, -1.07865833],
       [ 0.48501809, -1.14189403, -0.56677211]])
b=array([0., 0., 0.])


ValueError: matmul: dimension mismatch with signature (n,k=135),(k=3,m)->(n,m)

In [83]:
loss

NameError: name 'loss' is not defined

In [82]:
probs.argmax(axis=1) 

array([0, 0, 1, 1, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0,
       2, 2, 2, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 2, 2,
       1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 0, 0, 2, 0, 0, 1, 0, 0, 1, 2, 1, 0,
       2, 2, 1, 0, 2, 0, 2, 2, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 2, 1,
       0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 1, 2,
       1, 0, 0, 2, 1, 0, 0, 2, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1,
       2, 1, 0])