In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt

from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression

In [4]:
df = pd.read_csv('advertising.csv')
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [5]:
X=df.drop(columns=['Sales']).values
y=df['Sales'].values

In [6]:
stc_sc = StandardScaler()
make_poly = PolynomialFeatures(degree = 2, include_bias=False, interaction_only=True)
lin_reg = LinearRegression()

In [7]:
X = stc_sc.fit_transform(X)
X[:5]

array([[ 0.96985227,  0.98152247,  1.77894547],
       [-1.19737623,  1.08280781,  0.66957876],
       [-1.51615499,  1.52846331,  1.78354865],
       [ 0.05204968,  1.21785493,  1.28640506],
       [ 0.3941822 , -0.84161366,  1.28180188]])

In [8]:
X=make_poly.fit_transform(X)
X[:5]

array([[ 0.96985227,  0.98152247,  1.77894547,  0.95193179,  1.72531429,
         1.74607495],
       [-1.19737623,  1.08280781,  0.66957876, -1.29652833, -0.80173769,
         0.72502511],
       [-1.51615499,  1.52846331,  1.78354865, -2.31738727, -2.70413618,
         2.72608867],
       [ 0.05204968,  1.21785493,  1.28640506,  0.06338896,  0.06695697,
         1.56665475],
       [ 0.3941822 , -0.84161366,  1.28180188, -0.33174912,  0.50526348,
        -1.07878197]])

In [9]:
lin_reg.fit(X,y)

LinearRegression()

In [10]:
y_pred = lin_reg.predict(X)

In [11]:
lin_reg.score(X,y)

0.914582025610522

In [12]:
df = pd.read_csv('advertising.csv')
df.head()
X=df.drop(columns=['Sales']).values
y=df['Sales'].values

In [13]:
X.shape[0]

200

In [14]:
train_size = int(0.7*X.shape[0])
train_size

140

In [15]:
ix = np.random.permutation(X.shape[0])

In [16]:
X[ix]   #shuffled x

array([[219.8,  33.5,  45.1],
       [ 89.7,   9.9,  35.7],
       [238.2,  34.3,   5.3],
       [227.2,  15.8,  49.9],
       [199.8,   3.1,  34.6],
       [ 19.6,  20.1,  17. ],
       [ 53.5,   2. ,  21.4],
       [ 76.4,  26.7,  22.3],
       [137.9,  46.4,  59. ],
       [136.2,  19.2,  16.6],
       [ 16.9,  43.7,  89.4],
       [ 11.7,  36.9,  45.2],
       [240.1,  16.7,  22.9],
       [205. ,  45.1,  19.6],
       [123.1,  34.6,  12.4],
       [131.1,  42.8,  28.9],
       [163.5,  36.8,   7.4],
       [ 13.2,  15.9,  49.6],
       [ 23.8,  35.1,  65.9],
       [175.1,  22.5,  31.5],
       [214.7,  24. ,   4. ],
       [177. ,  33.4,  38.7],
       [139.5,   2.1,  26.6],
       [ 43. ,  25.9,  20.5],
       [228. ,  37.7,  32. ],
       [261.3,  42.7,  54.7],
       [239.9,  41.5,  18.5],
       [ 17.2,  45.9,  69.3],
       [129.4,   5.7,  31.3],
       [262.9,   3.5,  19.5],
       [ 39.5,  41.1,   5.8],
       [ 74.7,  49.4,  45.7],
       [ 31.5,  24.6,   2.2],
       [12

In [17]:
y[ix]

array([19.6, 10.6, 20.7, 19.8, 16.4,  7.6,  8.1, 11.8, 15. , 13.2,  8.7,
        7.3, 20.9, 22.6, 15.2, 16. , 18. ,  5.6,  9.2, 16.1, 17.4, 17.1,
       10.3,  9.6, 21.5, 24.2, 23.2, 12. , 11. , 17. , 10.8, 14.7, 11. ,
       13.2,  8.4,  7.6, 14. ,  5.5, 23.7, 20.7, 11.6, 17.6,  9.7, 18.3,
       25.4, 19.9, 15.5, 20.9, 21.8, 12.3, 11.5, 14. , 20.2, 17.9,  5.3,
        6.7, 17.8, 17.2, 16.5, 16.7, 15.6,  4.8, 13.2, 11.6, 16.7, 13.6,
       19.2, 14.6,  8. , 12.5, 17.3, 22.3, 25.4,  7. , 11.8, 10.9, 11.9,
       10.8, 18.4, 25.4, 10.1,  9.7, 21.7, 17.3, 11.9, 20.9, 17.7,  1.6,
       16.7, 10.4,  3.2,  6.6, 16.5, 17.3, 20. , 13.4, 16.4, 14.2, 16. ,
       17.4, 14.8, 21.2, 16.7, 14. , 20.7, 15.5,  7.3, 12.2, 22.1, 20.6,
       16.6, 10.7,  8.7, 10.1, 12.6, 17.5, 19.7, 11.3,  5.3, 10.5, 11. ,
       18. , 18.2,  5.9, 23.8, 16.7, 11.9, 17.5, 12.6, 19.6, 19.4, 26.2,
       16.9,  7.2, 25.5, 24.7, 14.6, 17.1,  6.6, 12. , 22.6, 17.1, 20.8,
       12.9, 22.2, 10.3, 17.9, 12. , 12.4, 20.5, 10

In [18]:
X_train=X[ix][:train_size]
X_test=X[ix][train_size:]
y_train, y_test=y[ix][:train_size], y[ix][train_size:]
X_train.shape, X_test.shape

((140, 3), (60, 3))

In [19]:
y_train.shape, y_test.shape

((140,), (60,))

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.3, random_state=42)

In [22]:
X_train[:5]

array([[156.6,   2.6,   8.3],
       [276.7,   2.3,  23.7],
       [205. ,  45.1,  19.6],
       [ 66.9,  11.7,  36.8],
       [ 76.4,  26.7,  22.3]])

In [23]:
stc_sc = StandardScaler()
make_poly = PolynomialFeatures(degree = 2, include_bias=False, interaction_only=True)
lin_reg = LinearRegression()

In [24]:
X_train = stc_sc.fit_transform(X_train)
X_train = make_poly.fit_transform(X_train)

In [25]:
lin_reg.fit(X_train, y_train)

LinearRegression()

In [26]:
lin_reg.score(X_train, y_train)

0.9196478612654126

In [27]:
from sklearn.metrics import root_mean_squared_error

In [28]:
y_pred = lin_reg.predict(X_train)

In [29]:
root_mean_squared_error(y_train, y_pred)

1.4916905393172804

In [30]:
X_test=stc_sc.transform(X_test)
X_test = make_poly.transform(X_test)

In [31]:
lin_reg.score(X_test, y_test)

0.8935794222827521